Ruby HEAD is causing issues on travis
From https://travis-ci.org/hgmnz/fernet/jobs/10899685:

```
$ gem query --local | grep bundler >/dev/null || gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such
name (https://rubygems.org/latest_specs.4.8.gz)
The command "gem install bundler" failed and exited with 2 during setup.
```